-- Enable Row Level Security (RLS) is recommended but for this MVP we will keep it simple.
-- Ideally you should set up policies if you are exposing this to the client directly.
-- Since we are using a Node.js backend with service role (or anon key with serverside logic), it's fine.

-- 1. Contacts Table
create table contacts (
  id bigint generated by default as identity primary key,
  hashed_contact text unique not null,
  type text check (type in ('phone', 'email')) not null,
  report_count int default 0,
  status text default 'safe', -- 'safe', 'under_review', 'flagged'
  last_reported_at timestamptz default now()
);

-- 2. Reports Table
create table reports (
  id bigint generated by default as identity primary key,
  contact_id bigint references contacts (id) not null,
  fraud_type text not null,
  description text,
  proof_path text,
  created_at timestamptz default now()
);

-- 3. Removal Requests Table
create table removal_requests (
  id bigint generated by default as identity primary key,
  contact_identifier text not null,
  reason text not null,
  created_at timestamptz default now()
);
